modLoader="javafml" #mandatory
loaderVersion="[34,35,36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="MIT"
issueTrackerURL="https://github.com/Affehund/Skiing/issues" #optional
[[mods]] #mandatory
modId="skiing" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Skiing Mod" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Affehund/Skiing/main/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/skiing/" #optional
logoFile="skiing.png" #optional
authors="Affehund" #optional
description='''You like skiing? Now you can do it in minecraft!'''
