modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU GPLv3"
issueTrackerURL="https://github.com/Affehund/Skiing/issues" #optional
[[mods]] #mandatory
modId = "skiing" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Skiing" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/skiing/" #optional
logoFile="logo.png" #optional
credits="Thanks to all the translators and testers" #optional
authors="Affehund" #optional
description = '''You like skiing? Now you can do it in minecraft!'''
[[dependencies.skiing]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.skiing]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
